#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/kedoxey/.conda/envs/OBModel_linux/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/kedoxey/.conda/envs/OBModel_linux/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/kedoxey/CRCNS/PyramidalCellSimulations/models/ModelDB/L5bPCmodelsEH/mod/x86_64/.libs/libnrnmech.so" "$@"
