run_NML: False          # download and run with NeuroML version of model otherwise use NEURON version
plot_morphology: True   # plot morphology of cell 
enable_syns: False       # include synaptic input
use_colormaps: False    # color synpases in the morphology plot with a colormap, i.e. each synapse has a unique color
save_pickle: False      # save simulation output to a pickle file
log_firing_rate: False

seed: 74                # random sead

record_LFP: False       # record LFP
depths: 4               # number of electrodes around soma
apical_depths: 0        # number of electrodes in apical distal dendrites  

# Poisson spike trains
num_poisson: 1          # number of Poisson instances
spk_freq: 40            # Poisson spike frequency   

nmldb_id: 'NMLCL000073' # NeuroML database cell id
publication: 'Hay2011'  # Main author and publication year of corresponding article
local: False            # if True use a local copy of a cell model, else download the model from the NeuroML database
model_name: ''          # if local is True, name of the model directory in models/local/
hocs_dname: ''          # if local is True, name of directory containing hoc file(s)
mod_dname: ''           # if local is True, name of directory containing mod files
cell_type: 'PYR'        # tag for cell type
cell_model: ''          # tag for AuthorYear of corresponding publication
cell_name: ''           # if local is True, name of cell, i.e. name of hoc file
 
syns_lb: 0              # lower bound of distance from soma for synapse location - 0 if not distibuted by distance from soma
syns_ub: 1              # upper bound 
syns_type: 'soma'       # synaptic input locations -  soma, basal, apical, basal_apical, basal_soma, apical_soma, basal_apical_soma, all
syns_source: 'HS'       # use synapses from Hay & Segev 2015 model
syns_weight: 1          # synaptic weight
num_syns_E: 50          # number of excitatory synapses
num_syns_I: 0           # number of inhibitory synapses
synsPerConn: 1          # number of synapses per connection
channel_toggles: {'Na': 1, 'Ca': 1, 'K': 1}   # strength of channels in channel_secs
channel_secs: 'soma'    # toggle channels of compartments in this group - soma, basal, apical, basal_apical, basal_soma, apical_soma, basal_apical_soma, all
add_soma: False         # include soma in synapse locations
add_bkg: False          # add background input

vinit: -80              # initial cell membrane potential
dt: 0.01                # dt for simulation
recordStep: 0.1         # recording time step

### Input parameters ###
input_amp: 0            # amplitude of injected current to soma
stim_delay: 350         # stimulus (synaptic or current) delay
stim_dur: 1000          # stimulus (synaptic or current) duration
sim_dur: 1500           # simulation duration


sim_name: 'DF'      # name for organizing batch simulations together, i.e. experiment type identifier
sim_flag: ''        # name for specific simulation
sim_label: ''       # label for simulation that includes identifiable parameters - populated in simulate_netpyne.py

sim_message: 'Simulation parameters for characterizing single cell dynamics with default parameters.'