run_NML: False
plot_morphology: True
enable_syns: True

seed: 74

record_LFP: False
depths: 4

spk_type: 'poisson'  # poisson or gaussian
# Poisson spike trains
num_poisson: 1
spk_freq: 40
spk_freq_lb: &sfl 40  # 20
spk_freq_ub: &sfu 41  # 120

nmldb_id: 'NMLCL000073'
publication: 'Hay2011'
 
syns_lb: &sl 0  # 0 if not distibuted by distance from soma
syns_ub: &su 1
syns_type: &st 'apical'  # soma, basal, apical, basal_apical, basal_soma, apical_soma, basal_apical_soma, all
syns_source: &ss 'HS'
syns_weight: &sw 1  # Hay & Segev 2015 (HS) = 1.5, Dura-Bernal et al. 2024 (DB) = 1
num_syns_E: &nse 50   # 10000
num_syns_I: &nsi 0   # 250
synsPerConn: &spc 1
channel_toggles: {'Na': 1, 'Ca': 1, 'K': 1}
channel_secs: 'soma' # soma, basal, apical, basal_apical, basal_soma, apical_soma, basal_apical_soma, all
add_soma: False
add_inh: False
add_bkg: False

vinit: -80
dt: 0.01
recordStep: 0.1

### Input parameters ###
input_amp: &in 0  # [0, 0.35477, 0.44346, 0.53215, 1.0643]
stim_delay: 350
stim_dur: 1000
sim_dur: 1500

# Gaussian spike trains
gauss_mean: 1.4
gauss_std: 0.4

# sim_name: &sn !join ['EXC-', *st]
sim_name: 'EXC'
sim_label: ''  # !join [*sn, '_', *nse, 'E', 'x', *sw]
sim_flag: ''
# sim_label: !join [*sn, '_', *sl, '-', *su, '_', *sf, 'Hz_', *ns, 'x', *spc, 'x', *sw, '_', *ss]

sim_message: 'Simulation parameters for characterizing cell dynamics with just excitatory synapses.'